### ISSUE TITLE
Add vim-vue compatibility

### ISSUE THREAD

**Issue by natematykiewicz** [yardnsm/vim-import-cost#26]
[vim-vue](https://github.com/posva/vim-vue) is a common plugin for editing `.vue` files. It would be great if this plugin was compatible with vim-vue, so that we could determine the import costs of JS inside a `.vue` file.

I see that `:ImportCost` is not available in a file where the filetype is `vue`.

I tried adding:
```
autocmd FileType vue             call <SID>InitCommands()
```

to plugin/import_cost.vim. This gives me an `:ImportCost` command, but running it returns the following error:

```
vim-import-cost: [error] SyntaxError: Expected corresponding JSX closing tag for <input> (8:6)
```

I'm not using JSX, but clearly something assumes it's JSX because of the HTML tags, and doesn't know that the only relevant thing for it to look at is inside the `<script></script>` in the file.

I'm not sure where to go from here.

I do see https://github.com/wix/import-cost/issues/23, so perhaps what I did is all that this plugin should have to do and the real bulk of the work needs to go in `wix/import-cost`?

**Comment by yardnsm** [comment]
Yeah, actual implementation should go right into the `import-cost` package that *this* plugin uses, so we need to wait until https://github.com/wix/import-cost/issues/23 is closed.

Adding the `autocmd` for Vue filetypes is probably the only change needed in this plugin.

**Comment by natematykiewicz** [comment]
I see https://github.com/wix/import-cost/issues/23 was closed saying it's out of scope, so I'll close this.
