### ISSUE TITLE
Question: does it work with non-webpack projects?

### ISSUE THREAD

**Issue by lfilho** [yardnsm/vim-import-cost#28]
I think the answer is "no" but wanted to confirm: does it work with non-webpack projects?

I have a pure Node 13+ project with ESM modules, without webpack. Would this plugin work?

If not, would you please consider it as a feature request? :)

Thanks!

**Comment by yardnsm** [comment]
Well, this plugin is only a "wrapper" on top the [`import-cost`](https://github.com/wix/import-cost/tree/master/packages/import-cost) node module that does all of the size calculation. You can find a explanation for the whole process in [this blog post](https://medium.com/wix-engineering/keep-your-bundle-size-under-control-with-import-cost-vscode-extension-5d476b3c5a76).

I'm guessing it should work for your case. If not, I suggest opening an issue in [wix/import-cost](https://github.com/wix/import-cost) repo.
