### ISSUE TITLE
Consider adding support for named imports

### ISSUE THREAD

**Issue by NKBelousov** [yardnsm/vim-import-cost#3]
Hi, thank you for the port!

It would be nice to see actual import size when importing named exports. I just experimented a bit with react-router-redux and it shows 32KB no matter what I'm importing: just replace function or the whole package.

**Comment by yardnsm** [comment]
Hey @NKBelousov! 

The same issue happens in the [origin plugin for VS code](https://github.com/wix/import-cost/tree/master/packages/vscode-import-cost). *This* vim plugin uses the same package used to calculate the size, which should support named imports (as it indeed does tree shaking). My guess is that `react-router-redux` doesn't tree-shake well.
