### ISSUE TITLE
Plugin opens :ImportCost text in separate vim-window

### ISSUE THREAD

**Issue by TimDaub** [yardnsm/vim-import-cost#33]
Here's what happened after I did `:ImportCost` on a .mjs file

<img width="887" alt="Screen Shot 2021-01-18 at 14 11 18" src="https://user-images.githubusercontent.com/2758453/104919794-1c9e4400-5997-11eb-9dde-5d0de5b0486c.png">

How did I install:

```bash
$ cd .vim/bundle && git clone <repo>
$ npm i
```

Then I opened vim and the above is my result. Let me know if you need more information.

**Comment by yardnsm** [comment]
Hey @TimDaub,

That's the desired behaviour. The virtual text rendering only works in Neovim. In Vim, the plugin will open a scratch buffer filled with the results.

**Comment by TimDaub** [comment]
Hey @yardnsm,

thanks for your reply. Is it possible to adjust the plugin to work with regular vim? If not, feel free to close the issue.

**Comment by yardnsm** [comment]
I'm not aware of a virtual text feature in regular Vim, so I think that's not possible at the moment :(
