### ISSUE TITLE
The import cost text color is too dark 

### ISSUE THREAD

**Issue by minhhieu1612** [yardnsm/vim-import-cost#35]
I write this issue on ver 2.0.
And on my terminal (Xfce terminal), I use the background image for this terminal and the text looks too dark and hard to see. 
Can you be happy to support this case?

Many thanks to the dev team.

**Comment by yardnsm** [comment]
The virtual text of this plugin uses a highlight called `ImportCostVirtualText`. You can customize it as you wish.

Hope that's helps!
